# Please fill out the following fields to customize your documentation site
site_name: Haptic Time of Flight Nosepoke Documentation
site_description: A nosepoke with vibration and analog distance sensing for neuroscience experiments
repo_url: https://github.com/Karpova-Lab/haptic-tof-nosepoke/
repo_name: Karpova-Lab/haptic-tof-nosepoke
site_author: Andy Lustig
copyright: Copyright &copy; 2024 Andy Lustig

extra:
    discussion_url: https://github.com/Karpova-Lab/haptic-tof-nosepoke/discussions
    issues_url: https://github.com/Karpova-Lab/haptic-tof-nosepoke/issues/new
    version:
        provider: mike
        alias: true

nav:
    - Overview: index.md
    - Electronics: electronics.md
    - Hardware: hardware.md
    - Software: software.md

docs_dir: src
site_dir: ../docs

theme:
    name: material
    custom_dir: overrides
    logo: _home.svg
    palette:
        primary: teal
        accent: grean
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.footer
        - navigation.instant
        - content.code.copy

extra_css:
    - _extra.css

plugins:
    - search
    - include-markdown:
          comments: false

markdown_extensions:
    - toc:
          title: On this page
          permalink: "#"
          toc_depth: 3
    - admonition
    - attr_list
    - md_in_html
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.snippets:
          base_path: src
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tabbed:
          alternate_style: true
